### PR TITLE
Python2 support.

### PR DESCRIPTION
**Pull request by mbr**
Two small fixes made, now the test suite runs on Python 2.7 as well as 3.4.

### CODE REVIEW

**Comment by simonzack** [comment]
I never really intended to have python 2 support, but since the fix is small enough, I'll merge. Thanks!

**Comment by mbr** [comment]
Thanks for merging. I had to abandon this plan, unfortunately, due to licencing issues. But I believe Python2 support is worthwhile nonetheless. =)

**Comment by simonzack** [comment]
@mbr What license are you after? I'm blind when it comes to this area and would be happy to switch to a better one.

**Comment by mbr** [comment]
Well, it usually boils down to one of three choices:
1. Strong Copyleft: GPLv2/v3. This is what you currently use; as a consequences anyone using your library must make his library/program copyleft (= GPL) as well. This is usually an okay choice for a program, but in a library, it becomes a very political thing ("you can use my stuff only if you make all of yours available too").
2. Weak Copyleft: LGPL. Means strong copyleft for you library but _doesn't_ force people using it to make their program GPL as well. Alterations to the library itself must be made open though. That'd be my preference if you care about copyleft.
3. No Copyleft: MIT/BSD/.../public domain. "Do what you want, but don't sue or plagiarize me" is the basic message. It's what I use and the most flexible.

So there. Anything but 1. is fine for a library =). Using a strong copyleft on a library is usually painful (see: readline) and only done if you really mean it, or want to sell it under a different license (see: Qt).

**Comment by simonzack** [comment]
@mbr Ok done :)

**Pull request merged**
